name: 'Setup Node.js'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: '>=7'
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
        cache-dependency-path: '**/package-lock.json'

    - run: pnpm i --frozen-lockfile
      shell: bash
