name: 'Setup PNPM'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: '>=7'
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'
