name: "CI Styles"

on:
  pull_request:
    branches:    
      - main
      - dev
    paths:
      - "**.s?css"
      - .github/workflows/ci-styles.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - run: npm run stylelint
      - run: npm run format