name: 'Apps Web Tests'

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'packages/ui/**'
      - 'packages/eslint-config-base/**'
      - 'packages/eslint-config-react/**'
      - 'packages/stylelint-config-base/**'
      - 'packages/tailwindcss/**'
      - 'packages/tsconfig/**'
      - .github/workflows/pr-test-apps-web.yml
      - '!**/README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: setup-node
        uses: ./.github/actions/setup-node

      - name: Format
        id: format
        run: pnpm --filter @ytk6565.net/ui format

      - name: Typecheck
        id: typecheck
        run: pnpm --filter @ytk6565.net/ui typecheck

      - name: Lint
        id: lint
        run: pnpm --filter @ytk6565.net/ui lint

      - name: Unit test
        id: build
        run: pnpm --filter @ytk6565.net/ui test

      - name: Build Storybook
        id: build
        run: pnpm --filter @ytk6565.net/ui build-storybook
