name: 'Packages UI Tests'

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
  CONTENTFUL_MANAGEMENT_API_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_API_ACCESS_TOKEN }}
  CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'packages/ui/**'
      - 'packages/domain/**'
      - 'packages/eslint-config-base/**'
      - 'packages/eslint-config-react/**'
      - 'packages/stylelint-config-base/**'
      - 'packages/tailwindcss/**'
      - 'packages/tsconfig/**'
      - .github/workflows/pr-test-packages-ui.yml
      - '!**/README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build dependencies
        run: pnpm run build --filter @ytk6565.net/ui

      - name: Format
        run: pnpm --filter @ytk6565.net/ui format

      - name: Typecheck
        run: pnpm --filter @ytk6565.net/ui typecheck

      - name: Lint
        run: pnpm --filter @ytk6565.net/ui lint

      - name: Stylelint
        run: pnpm --filter @ytk6565.net/web stylelint

      - name: Unit test
        run: pnpm --filter @ytk6565.net/ui test -- run

      - name: Build Storybook
        run: pnpm --filter @ytk6565.net/ui build-storybook
