name: 'Packages Infrastructure Tests'

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
  CONTENTFUL_MANAGEMENT_API_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_API_ACCESS_TOKEN }}
  CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'packages/infrastructure/**'
      - 'packages/domain/**'
      - 'packages/eslint-config-base/**'
      - 'packages/tsconfig/**'
      - .github/workflows/pr-test-packages-infrastructure.yml
      - '!**/README.md'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: ./.github/actions/setup-pnpm

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build dependencies
        run: pnpm run build --filter @ytk6565.net/infrastructure

      - name: Format
        run: pnpm --filter @ytk6565.net/infrastructure format

      - name: Typecheck
        run: pnpm --filter @ytk6565.net/infrastructure typecheck

      - name: Lint
        run: pnpm --filter @ytk6565.net/infrastructure lint

      - name: Unit test
        run: pnpm --filter @ytk6565.net/infrastructure test -- run
